train: /home/mfa/My_Data/Semester1/ML/iToBoS/split_dataset/train/images
val: /home/mfa/My_Data/Semester1/ML/iToBoS/split_dataset/val/images
test: /home/mfa/My_Data/Semester1/ML/iToBoS/split_dataset/test/images  # Optional
nc: 1                              # Number of classes
names: ['lesion']                  # Class names
imgsz: 873
epochs: 100
exist_ok: true
pretrained: true
optimizer: auto
verbose: true
rect: true
batch: 6
workers: 4
project: runs/
lr0: 0.01
lrf: 0.01
momentum: 0.937
mask_ratio: 4
dropout: 0.0
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
iou: 0.7
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
cfg: null
tracker: botsort.yaml
save_dir: runs/fine_tune_yolov9e/exp



